name = "LearnBase"
uuid = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
version = "0.6.0"

[compat]
julia = "1.0"

[extras]
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SparseArrays"]
